# Generated by Django 5.2.3 on 2025-10-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='submitted_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='correct_answer',
            field=models.CharField(default='correct answer here', max_length=255),
        ),
    ]
