# Generated by Django 5.2.3 on 2025-10-02 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_action_submitted_answer_round_correct_answer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='round',
            unique_together={('game', 'round_number')},
        ),
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='game.game')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_scores', to='game.participant')),
            ],
            options={
                'unique_together': {('game', 'participant')},
            },
        ),
    ]
