# Generated by Django 5.2.3 on 2025-10-10 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_round_unique_together_gamescore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobbies', to='game.game')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='participant',
            name='current_lobby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='game.lobby'),
        ),
        migrations.AddField(
            model_name='round',
            name='lobby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game.lobby'),
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together={('lobby', 'round_number')},
        ),
    ]
