# Generated by Django 5.2.3 on 2025-10-10 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_lobby_alter_round_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='round',
            unique_together={('game', 'lobby', 'round_number')},
        ),
    ]
