# Generated by Django 5.2.3 on 2025-10-10 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_round_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='round',
            unique_together={('game', 'round_number')},
        ),
        migrations.RemoveField(
            model_name='round',
            name='lobby',
        ),
    ]
